version: '3'
services:
  testin8000:
    build: testin8000
    container_name: testin8000
    image: sppp-test-stand-testin8000
    ports:
      - 8000:8000

  proxy8021:
    build: proxy8021
    container_name: proxy8021
    image: sppp-test-stand-proxy8021
    ports:
      - 8021:8021
  proxy8022:
    build: proxy8022
    container_name: proxy8022
    image: sppp-test-stand-proxy8022
    ports:
      - 8022:8022

  sppp8011:
    build: sppp8011
    container_name: sppp8011
    image: sppp-test-stand-sppp8011
    ports:
      - 8011:8011
  sppp8012:
    build: sppp8012
    container_name: sppp8012
    image: sppp-test-stand-sppp8012
    ports:
      - 8012:8012

  app8031:
    build: app8031
    container_name: app8031
    image: sppp-test-stand-app8031
    ports:
      - 8031:8031
  app8032:
    build: app8032
    container_name: app8032
    image: sppp-test-stand-app8032
    ports:
      - 8032:8032
